version: '3.0' # specifying the version of docker-compose
services:
    webserver:
      build:  # building the docker-image using docker file
       context: .
       dockerfile: Dockerfile
      environment:
          NODE_ENV: production # specifying the enviornment
      networks:
         - frontend
      ports:
         - "8082:8080"  # port-mapping
    mysql:  # database service
       image: mysql:latest
       volumes:
          - db_data:/var/lib/mysql # volume path
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: admin
         MYSQL_DATABASE: admin12
         MYSQL_USER: admin
         MYSQL_password: admin123
       ports:
          - "3306:3306"
       networks:
        - backend
networks:
    frontend:
       driver: bridge
    backend:
      driver: bridge
volumes:   # declaring the volumes
   db_data:
     driver: local
